### ISSUE TITLE
ClientID & Secret rather than realm_public_key

### ISSUE THREAD

**Issue by lancemitchell** [robsontenorio/laravel-keycloak-guard#1]
Hello, I am using the latest version of keycloak (4.3.0.Final) which encourages ClientID & Secret with a URL redirect. 

I do not see where I would configure this into your application? 

The use of a Realm Public Key is not encouraged as our IT security policy calls for periodic rotation of Realm Key Pairs. It would be much better to configure my Laravel Application on a per-client, rather than per-realm basis. Are you looking to implement this into this code?

What am I missing?

**Comment by robsontenorio** [comment]
The current version relies on Realm Public Key. But, client ID and secret is an alternative. Can you share docs and specifications about this issue?

**Comment by lancemitchell** [comment]
Thanks for responding. 
Here are the issues in a nutshell

**Bit of Background**
I have implement Keycloak with other PHP Apps using the best practice
[https://www.keycloak.org/docs/3.3/server_admin/topics/sso-protocols/oidc.html](OIDC Authorization Code Flow). In that scenario I opted for the "confidential client" option that uses a client id/secret combination instead of the "Public clients" option as I could secure the secret in a PHP backend file. 

So I was looking for similar way to implement OpenID Connect with Laravel 5.6 and your package seemed to be the only Laravel turn-key and maintained solution available.

**Issues with laravel-keycloak-guard**
I have spent the last 2 days trying to implement laravel-keycloak-guard for Laravel 5.6 with the latest Keycloak 4.2.1.Final and faced some serious hurdles

1. The documentation is incomplete on how to configure Laravel; 

(a) to enable laravel-keycloak-guard to act as a API / WEB guard during routing; configuring config/auth.php is simply the start. I had to also configure config/app.php to add **KeycloakGuard\KeycloakGuardServiceProvider::class**. 

(b) But even that Laravel configuration is not enough; as there is no mention of how the user will be redirected from Laravel to Keycloak in "step 1" of your "the flow" diagram to acquire a token. So I ended up experimenting with the following routing hacks

```
Route::get('/login', function () {
    return redirect('https://<KEYCLOAK_HOST>/auth/realms/<KEYCLOAK_REALM>/protocol/openid-connect/auth?response_type=code&redirect_uri=<KEYCLOAK_REDIRECT_URI>&client_id=<KEYCLOAK_CLIENT_ID>&scope=openid');
})->name('login');

Route::get('/logout', function () {
    return redirect('https://<KEYCLOAK_HOST>/auth/realms/<KEYCLOAK_REALM>/protocol/openid-connect/logout?redirect_uri=<KEYCLOAK_REDIRECT_URI>');
})->name('logout');

```
(c) There is no mention in laravel-keycloak-guard Installation on which controller should handle the Keycloak redirect response for token processing, so I guessed the default Laravel Login Controller
```
Route::get('<KEYCLOAK_REDIRECT_URI>', [
  'as' => '',
  'uses' => 'Auth\LoginController@login'
]);
```
But there is code in Illuminate\Foundation\Auth\AuthenticatesUsers:validateLogin() that expects **"username"** and **"password"** in the authentication response and that is NOT what Keycloak will send to Laravel. 

This is a **MAJOR**  BLOCKER  that I have no solution for?
Can you enlighten as to how you implemented this in your Laravel implementation?

2. But even after all that; laravel-keycloak-guard cannot work because laravel-keycloak-guard [KeycloakGuard.php](https://github.com/robsontenorio/laravel-keycloak-guard/blob/master/src/KeycloakGuard.php) expects to receive a token from Keycloak as **$this->request->bearerToken()**

BUT the [Keycloak docs](https://www.keycloak.org/docs/latest/server_admin/index.html) says

> The Keycloak authentication server will attempt to authenticate the user and return a JSON body containing an OAuth-style Bearer token

> bearer-only - Bearer-only access type means that the application only allows bearer token requests. If this is turned on, this application cannot participate in browser logins.

Which leads me to believe that the **OIDC Authorization Code Flow** workflow I need uses redirects not API JSON communication.  To illustrate what I am receiving, here is the **code** query string parameter storing the token response that I get from Keycloak.  I don't know how to change this behavior?

`state=ff2490912dd7099328b610f724316c5c&session_state=c429c25c-58ed-4e6b-811c-c22a19034de3&code=eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..ENzxQ5Ql_lcB7bnoRIhq4Q.yA_hZtGbypct03sh5jOgQAL-75ECpk-fTdbKly7Jslq3f3_4MYpFUO4kqw_IjUgdkbHyH1YfeLm6HhqNPcUhll66gtG3MiOjAtEQ6kOltAUgrDRbdOax9z0wfi1gwslH2x7aqUM2LTBbwTIbz8SWYIoxM-ziSVUFeYNvJGbMpYD9fAhLO3NRVNmZERN9fA6eKB7AyvwwBTm788UOYTT5cQ5UAkUKHIhDOblG3DyxcqX-sEHz2jQrS78R5GBwNMMp.4q0tA1BRtsbX7FpM_-NZkg`

Does your experience with Laravel and Keycloak lend towards any insights as to what's wrong?

**Comment by robsontenorio** [comment]
There are too much on this first issue. Let’s break it into smaller parts :)

For this conversation, please, keep in mind the CURRENT IMPLEMENTATION.

1) This package is just a simple “Guard”. As Laravel Official Doc says: it just validate if something can be authenticated, based on some rules.  In this case we rely on Keycloak token. But it could be any kind of token. 

2) Did you understand the “requirements” and basic workflow? This package does not redirect to anywhere and is not responsible for issuing any token. It just validate the token (based on realm public key). 

3) For full understanding, you can try it with a fresh Laravel project. So, I can guide you if you missed something.

**Comment by lancemitchell** [comment]
Thanks for following up
my blockers with implementing laravel-keycloak-guard in OATH2 are very specific
1. This IS a fresh Laravel project. I am relying on your instructions and my Keycloak documentation to get a fully working implementation functional. Its clearly not enough :)
2. HOW did you get Laravel to process the token response from Keycloak in Laravel's default Auth out-of-box infrastructure. Its documented that you are not using Passport. Its not magic, its very specific
3. HOW did you get the token? in the response Header? in a query string? What was the parameter name?

**Comment by lancemitchell** [comment]
I'm digging deeper into the [Laravel documentation on Socialite](https://laravel.com/docs/5.6/socialite)
Not sure why there is [not already a provider for Keycloak](https://socialiteproviders.github.io/about.html)

**Comment by robsontenorio** [comment]
1. Can you share your fresh Laravel project into a Github repo? So I can digg it. 

2. The package already has a service provider, that implement the guard. 

3. Keep in mind, as described on Readme (The Flow), that frontend is responsible for issuing the token on Keycloak Server. The backend project (API/Laravel Project), has nothing to do with it. So, don’t need Passport, I just need validate if the tokenJWT is valid (based on realm public key). 

The frontend requests includes a Baerer jwt token on authorization headers.

**Comment by robsontenorio** [comment]
For sure, in your scenario is the best option ;)

**Comment by nmbatingal** [comment]
@lancemitchell Hello!

Can you share to me how you use laravel socialite in getting token from keycloak server?
Thank you :)

**Comment by lancemitchell** [comment]
Attached is my keycloak socialite implementation.
[Socialite-Keycloak-Provider-Implementation.zip](https://github.com/robsontenorio/laravel-keycloak-guard/files/4422675/Socialite-Keycloak-Provider-Implementation.zip)

The code performs authentication and authorization
Feel free to start up a Github repo for it, or contribute it to [Socialite Providers - A Collection of Providers for Laravel Socialite](https://socialiteproviders.netlify.com) I would appreciate the credit :-)
