### ISSUE TITLE
Call to undefined method KeycloakGuard\KeycloakGuard::attempt()

### ISSUE THREAD

**Issue by Jenkiiz** [robsontenorio/laravel-keycloak-guard#10]
Hello ,

I'm getting this error while trying to connect to my small application.

What did I do wrong ? 

Here is my project : https://github.com/Jenkiiz/test_guard.git

Thank you !

**Comment by robsontenorio** [comment]
@Jenkiiz Make sure you followed all steps from README. Your .env file does not contain keycloak vars

**Comment by Jenkiiz** [comment]
Yep did it 
Also added "KeycloakGuard\KeycloakGuardServiceProvider::class," to config/app.php
Still having the same issue

**Comment by vino-jasuba** [comment]
@Jenkiiz, did you manage to fix this?

**Comment by robsontenorio** [comment]
Please, if this is still a issue fill a new issue. Your repo does not exists.
