### ISSUE TITLE
500 Error if the token expired.

### ISSUE THREAD

**Issue by info170** [robsontenorio/laravel-keycloak-guard#104]
If access token expires I got the error:
KeycloakGuard\Exceptions\TokenException: [Keycloak Guard] Expired token in file /var/www/html/vendor/robsontenorio/laravel-keycloak-guard/src/KeycloakGuard.php on line 42

As I think, it should recall new access_token using refresh_token ?

**Comment by robsontenorio** [comment]
If anyone send an expired token and this package simple issue a new fresh it would be a security issue. 

By design It is client responsibility to manage token expirations.
