### ISSUE TITLE
Only works on GET Method ?

### ISSUE THREAD

**Issue by raj-saroj-vst-au4** [robsontenorio/laravel-keycloak-guard#105]
for context am using Laravel 10 as backend and Nuxtjs 3.9 for frontend. Whenever i call an api using GET with authorization headers, it works but, when i call the api changing it to POST it gives error. Was it meant to be used this way or am i missing out on something ?

**Comment by desod-vn** [comment]
can you describe exactly problem with image, code, flow

**Comment by raj-saroj-vst-au4** [comment]
Got it, was sending jwt from nuxt but i also needed to pass x-xsrf-token in the headers. Thanks, closing with this
