### ISSUE TITLE
[Keycloak Guard] Signature verification failed

### ISSUE THREAD

**Issue by shineirvin** [robsontenorio/laravel-keycloak-guard#11]
Im getting this error message after trying to access an url with access_token bearer. I did setup the required parameter .env 

What did I do wrong ?

**Comment by vino-jasuba** [comment]
@shineirvin, this  error is raised when you supply an invalid token. Check the token you're passing as the `access_token` and ensure that: 

1. Was generated by the Keycloak instance whose public key you've set in your `.env`
2. That you copied the entire key

**Comment by robsontenorio** [comment]
Please, if it is still a issue fill a new issue providing more details.
