### ISSUE TITLE
how to integrate

### ISSUE THREAD

**Issue by ostri** [robsontenorio/laravel-keycloak-guard#12]
I've installed the laravel-keycloak-guard like instructed, but I am getting the error.
Do I need to do something that is not documented to make this work?

API works well without keycloak-guard

Thanks in advance.

my configuration:
        "php": "^7.1.3",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "5.8.*",
        "laravel/tinker": "^1.0",
        "robsontenorio/laravel-keycloak-guard": "^1.3"

error stack trace.

InvalidArgumentException thrown with message "Route [login] not defined."

Stacktrace:
#35 InvalidArgumentException in /home/ostri/sites/l2/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:388
#34 Illuminate\Routing\UrlGenerator:route in /home/ostri/sites/l2/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:782
#33 route in /home/ostri/sites/l2/app/Http/Middleware/Authenticate.php:18
#32 App\Http\Middleware\Authenticate:redirectTo in /home/ostri/sites/l2/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php:68
#31 Illuminate\Auth\Middleware\Authenticate:authenticate in /home/ostri/sites/l2/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php:41
#30 Illuminate\Auth\Middleware\Authenticate:handle in /home/ostri/sites/l2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#29 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/ostri/sites/l2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#28 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/ostri/sites/l2/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php:58
#27 Illuminate\Routing\Middleware\ThrottleRequests:handle in /home/ostri/sites/l2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#26 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/ostri/sites/l2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#25 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/ostri/sites/l2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:104
#24 Illuminate\Pipeline\Pipeline:then in /home/ostri/sites/l2/vendor/laravel/framework/src/Illuminate/Routing/Router.php:682
#23 Illuminate\Routing\Router:runRouteWithinStack in /home/ostri/sites/l2/vendor/laravel/framework/src/Illuminate/Routing/Router.php:657
#22 Illuminate\Routing\Router:runRoute in /home/ostri/sites/l2/vendor/laravel/framework/src/Illuminate/Routing/Router.php:623
#21 Illuminate\Routing\Router:dispatchToRoute in /home/ostri/sites/l2/vendor/laravel/framework/src/Illuminate/Routing/Router.php:612
#20 Illuminate\Routing\Router:dispatch in /home/ostri/sites/l2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:176
#19 Illuminate\Foundation\Http\Kernel:Illuminate\Foundation\Http\{closure} in /home/ostri/sites/l2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
#18 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/ostri/sites/l2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21
#17 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in /home/ostri/sites/l2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#16 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/ostri/sites/l2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#15 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/ostri/sites/l2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21
#14 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in /home/ostri/sites/l2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#13 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/ostri/sites/l2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#12 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/ostri/sites/l2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:27
#11 Illuminate\Foundation\Http\Middleware\ValidatePostSize:handle in /home/ostri/sites/l2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#10 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/ostri/sites/l2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#9 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/ostri/sites/l2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php:62
#8 Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode:handle in /home/ostri/sites/l2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#7 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/ostri/sites/l2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#6 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/ostri/sites/l2/vendor/fideloper/proxy/src/TrustProxies.php:57
#5 Fideloper\Proxy\TrustProxies:handle in /home/ostri/sites/l2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#4 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/ostri/sites/l2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#3 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/ostri/sites/l2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:104
#2 Illuminate\Pipeline\Pipeline:then in /home/ostri/sites/l2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:151
#1 Illuminate\Foundation\Http\Kernel:sendRequestThroughRouter in /home/ostri/sites/l2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:116
#0 Illuminate\Foundation\Http\Kernel:handle in /home/ostri/sites/l2/public/index.php:55

**Comment by robsontenorio** [comment]
`InvalidArgumentException thrown with message "Route [login] not defined."` is related to `web` middleware. This packages works for `api` middleware.

Make sure you are calling `api` endpoints not `web` controllers.

**Comment by robsontenorio** [comment]
Please, if it is still a issue fill a new issue providing more details.

**Comment by avragavan** [comment]
yes im also getting the same error with api - keycloak
