### ISSUE TITLE
Exception handling

### ISSUE THREAD

**Issue by thoss** [robsontenorio/laravel-keycloak-guard#13]
Hi,

is it possible to add an Exception Handler?

I would prefer a 4xx Http Status Code with a message instead of a 500 Server error in some cases.

For example the ResourceAccessNotAllowedException 

=> 403 - You do not have the resource access

Best regards

thoss

**Comment by thoss** [comment]
I have fixed this with the global Laravel Exception handler.
If it is not intended to add a specific ExceptionHandler, you can close this issue :)

**Comment by robsontenorio** [comment]
For now i would suggest you to stick with global handler.
