### ISSUE TITLE
Registration flow

### ISSUE THREAD

**Issue by w1n** [robsontenorio/laravel-keycloak-guard#14]
If I store some information about users in Laravel App Database (Users table)
So I have same users in DB:
1. Keycloak
2. Laravel App (some additional user information)

KEYCLOAK_LOAD_USER_FROM_DATABASE = true

How can I organize registration flow with your package to store users in both databases?

**Comment by robsontenorio** [comment]
I am afraid this package cannot help you by itself. This package auto-load already registered users in laravel database.  You must implement by yourself additional registration mechanisms for new users. 

In the future a "auto-register user"  would be a nice feature! PR are welcome :)

**Comment by frital** [comment]
Hi @robsontenorio !! 

I'm working on this sync with the database, and open a PR. All looks good, BUT i can't understand why i have no success by calling any eloquent method (like save() or updateOrCreate()) inside the KeycloakGuard Class. And i can'T catch the error in logs. =(

Maybe you can give some orientation, to fix this PR and, if you agree, then later be able to join to this very helpful package!!

Thx a lot in advance!! 

PS.: Abracao pra Brasilia, de um Paracatuense, que no momento esta em Frankfurt, mas esta voltando pro BR em breve! =)
