### ISSUE TITLE
Requests to secured api route fail very strangely

### ISSUE THREAD

**Issue by Req** [robsontenorio/laravel-keycloak-guard#15]
I'm trying to implement a similar setup to the example. My frontend authenticates with KeyCloak and I make a test request to the backend. My test request is `GET /api/v1/bla` and has a header `Authorization: Bearer eyJhbG...`. When I refresh my browser, my frontend identifies the KC session as active and working. My user is identified via email in Laravel and in the KC.

My test route:
```
  Route::group(['middleware' => 'auth:api'], function () {
      Route::get('bla', function () {
          Log::debug("boo");
          return JsonResponse::create(["T" => 23], 200);
      });
});
```
My network tab:
![image](https://user-images.githubusercontent.com/635732/76205417-d9b20280-6202-11ea-8ab3-6714afe165d1.png)

So, the 1st time I call **bla**, it timeouts after ~3.1 minutes. Then the 2nd time it works (wtf) and then the 3rd time it responds with `{"code":500,"message":"[Keycloak Guard] Expired token"}`.

Could it be that I have configured something somewhere incorrectly? I don't know where to look or where to start, I'm completely lost. I want to handle all authorization myself in the Laravel app, I just want to authenticate the user with KC and map them to a Laravel user.

**Comment by robsontenorio** [comment]
I am not sure what directions give to you. 
But for sure, there are anything else interfering. Like another package or even laravel configuration. Try to remove authentication and hit /bla endpoint. 

Please, share your composer.json

**Comment by Req** [comment]
I tried moving the bla endpoint to outside of  `Route::group(['middleware' => 'auth:api'], function () { } );` and it still does the same thing. Requests that have the `Bearer ...` header all act like this, requests without the Bearer work fine.

The composer.json is a bit long, sorry! This won't allow me to attach it as a file, so here it is directly:
```{
  "name": "laravel/laravel",
  "description": "The Laravel Framework.",
  "keywords": [
    "framework",
    "laravel"
  ],
  "license": "MIT",
  "type": "project",
  "repositories": [
    {
      "type": "vcs",
      "url": "git@bitbucket.org:mediasignal/laravel-azure-ad-oauth.git"
    }
  ],
  "require": {
    "astrotomic/laravel-translatable": "^11.1",
    "barryvdh/laravel-cors": "^0.11.2",
    "barryvdh/laravel-ide-helper": "^2.3",
    "darkaonline/l5-swagger": "5.8.*",
    "doctrine/dbal": "< 2.7",
    "guzzlehttp/guzzle": "6.3.*",
    "laravel/framework": "5.8.*",
    "laravel/tinker": "^1.0",
    "mikehaertl/phpwkhtmltopdf": "^2.4",
    "mockery/mockery": "^1.2",
    "phpunit/phpunit": "^7.5",
    "pusher/pusher-php-server": "^4.0",
    "robsontenorio/laravel-keycloak-guard": "^1.3",
    "spatie/db-dumper": "^2.11",
    "spatie/laravel-permission": "^2.36"
  },
  "require-dev": {
    "deployer/deployer": "6.2",
    "filp/whoops": "~2.0",
    "friendsofphp/php-cs-fixer": "^2.13",
    "laravel/telescope": "^2.0"
  },
  "autoload": {
    "classmap": [
      "database"
    ],
    "psr-4": {
      "App\\": "app/"
    }
  },
  "autoload-dev": {
    "classmap": [
      "tests/TestCase.php"
    ],
    "psr-4": {
      "Tests\\": "tests/"
    }
  },
  "scripts": {
    "post-autoload-dump": [
      "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
      "@php artisan package:discover"
    ],
    "post-install-cmd": [
      "php artisan clear-compiled"
    ],
    "post-update-cmd": [
      "php artisan clear-compiled"
    ],
    "post-create-project-cmd": [
      "php -r \"copy('.env.example', '.env');\"",
      "php artisan key:generate"
    ],
    "generate-laravel-helpers": [
      "php artisan ide-helper:generate",
      "php artisan ide-helper:models --write",
      "php artisan ide-helper:meta"
    ],
    "clean-storage": [
      "php artisan archive:clean",
      "php artisan chunks:clean",
      "php artisan files:clean -f"
    ],
    "php-cs-fixer": [
      "php vendor/bin/php-cs-fixer fix --config=.php_cs.dist ./app ./config ./database ./resources ./tests"
    ],
    "php-cs-fixer:check": [
      "php vendor/bin/php-cs-fixer fix --dry-run -v --config=.php_cs.dist --using-cache=no ./app ./config ./database ./resources ./tests"
    ]
  },
  "config": {
    "preferred-install": "dist",
    "sort-packages": true,
    "optimize-autoloader": true,
    "platform": {
      "php": "7.1.3"
    }
  }
}
```

**Comment by Req** [comment]
I just noticed that if I intentionally add an invalid token, the timeout does not happen. If the token is invalid, unauthenticated routes just work normally and routes that require authentication return

`Keycloak Guard] Wrong number of segments {"exception":"[object] (KeycloakGuard\\Exceptions\\TokenExcep
tion(code: 0): [Keycloak Guard] Wrong number of segments at /var/www/html/vendor/robsontenorio/laravel-keycloak-guard/src/KeycloakGuard.ph
p:41) `

I still really don't have any solid ideas what to do, I am kind of trying random things

**Comment by Req** [comment]
Yet another update. I deleted my docker images, containers and deleted my vendors folder and rebuilt everything. Now I get a straight up `Status Code: 401 Unauthorized` for the secure endpoint when I have the valid bearer token. When I have an invalid token I still get `local.ERROR: [Keycloak Guard] Wrong number of segments`.

I am incredibly confused.

**Comment by robsontenorio** [comment]
Maybe related to “ "git@bitbucket.org:mediasignal/laravel-azure-ad-oauth.git"

Try remove it.

**Comment by Req** [comment]
That repo wasn't actively used (historical garbage :sweat_smile:), but yeah I removed it now and it still behaves the same.

**Comment by Req** [comment]
I have debugged the issue further and the requests all hang on `/vendor/laravel/framework/src/Illuminate/Auth/EloquentUserProvider.php`

There is the `retrieveByCredentials` function that returns the relevant user with an eloquent query like so: `$query->first();`. This query hangs forever and stops the process. Dumping the query it seems that the DB credentials look correct and doing a ->toSql() I see that it's trying to do `select * from `users` where `email` = ? and `users`.`deleted_at` is null`, which looks correct to me.

In my users database I have the correct user: 
```
MySQL [avainiacore]> select id, email from `users` where `email` = 'joel.peltonen@example.org and `users`.`deleted_at` is null;
+----+------------------------------+
| id | email                        |
+----+------------------------------+
|  4 | joel.peltonen@example.org |
+----+------------------------------+
```
And the $credentials inside KeycloakGuard.php::validate is `["email"=>"joel.peltonen@example.org"]`, which looks correct to me.

Any ideas?

In my Kernel.php I have

```
    'defaults' => [
        'guard' => 'api',
        'passwords' => 'users',
    ],
    'guards' => [
            'driver' => 'keycloak',
            'provider' => 'users',
        ],
    ],
    'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\User::class,
        ],
    ]
```

It would be really great if you could provide a working example of this being used, like a Demo repository.

**Comment by robsontenorio** [comment]
Just noticed you are using laravel 5.8. Really I have not tested on this version. If confirmed I will restrict compatibility for laravel 6+. I don’t know if it is related.

**Comment by Req** [comment]
I updated to `"laravel/framework": "6.0.*",` and `PHP 7.4.3`, it didn't make any difference :( I even changed Keycloak servers to use one that's hosted on an actual server and not in my local docker.

**Comment by Req** [comment]
If you can point to any working setup that would be a great help, I'm kind of desparate at this point. It seems like this is the perfect solution for me, but I just don't know what to do.

**Comment by Req** [comment]
We just can't get this thing to work at all. I've had 2 different devs and myself try to fix it but I finally have to abandon the project. 

Finally I removed this and went the DIY route defined in https://hackernoon.com/the-simple-and-efficient-way-to-enable-jwt-auth-in-laravel-a517c3202 and it worked immediately. From start to working auth it took me about 15 minutes to DIY the JWT decode and user matching using that blog post.

If there was just some working example or _anything_ we could have tried I would have loved to use this, but I just can't justify any more time after tens of hours of trial and error.
