### ISSUE TITLE
Lumen - Integração 

### ISSUE THREAD

**Issue by phmiranda** [robsontenorio/laravel-keycloak-guard#27]
Bom dia Robson, tudo bem ?
Estou precisando integrar o Lumen com o keycloak em uma API, você teria alguma documentação ou projeto de teste com esse pacote implementado ? Estou tendo dificuldades de entender como funciona o pacote criado por ti ou um da [Vizir](https://github.com/Vizir/laravel-keycloak-web-guard).

**Comment by robsontenorio** [comment]
Hi,

A recent PR added Lumen support. Please, check README. 

About another package from Vizir is a explicit copy from my package “not authorized” by me.
