### ISSUE TITLE
The decoded JWT token has not a valid `resource_access` allowed by API. Allowed resources by API:  in file 

### ISSUE THREAD

**Issue by pimly4x** [robsontenorio/laravel-keycloak-guard#29]
I get below error when make a reguest to my APi

KeycloakGuard\Exceptions\ResourceAccessNotAllowedException: [Keycloak Guard] The decoded JWT token has not a valid `resource_access` allowed by API. Allowed resources by API:  in file C:\xampp\htdocs\psyphy\psyphy\lead_service\vendor\robsontenorio\laravel-keycloak-guard\src\KeycloakGuard.php on line 164

**Comment by robsontenorio** [comment]
Please, see README. You must inform resource_access field on .env file

**Comment by pimly4x** [comment]
Nice. thank you.
