### ISSUE TITLE
Custom Request redirect

### ISSUE THREAD

**Issue by sascha284** [robsontenorio/laravel-keycloak-guard#33]
If I create a custom request in my API like `CustomerRequest` and put in a `required|string|max:50`. Auth redirects directly to login page if it returns false. Especally in API this is not very usefull. Does anybody know, how to get ErrorHandling ?

**Comment by robsontenorio** [comment]
This package is supposed to be used on Laravel API mode only. If there is some redirect on you API, may be you are on wrong path.
