### ISSUE TITLE
Unable to get Auth::user() or Auth::check() response in blade files

### ISSUE THREAD

**Issue by Mounika-12** [robsontenorio/laravel-keycloak-guard#34]
I am able to get the default methods response in controller files. But when I try to call the same methods in blade files like below

<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    
    <body>
       Welcome {{Auth::user()}}
    </body>
</html>`

Getting empty response in the view. Please help me where I am going wrong?

**Comment by robsontenorio** [comment]
See #31
