### ISSUE TITLE
"[Keycloak Guard] Cannot handle token prior to" message

### ISSUE THREAD

**Issue by haizad** [robsontenorio/laravel-keycloak-guard#38]
Hi 

I got the error message of
```
KeycloakGuard\Exceptions\TokenException
[Keycloak Guard] Cannot handle token prior to 2020-12-02T01:54:16+0000
```
when try to verify the _access_token_.

My route is

```
Route::group(['middleware' => 'auth:api'], function () {
    Route::get('/protected', function () {
        return Auth::token();
    });
});

```

The route did returns full decoded JWT token from authenticated user only after several seconds after the token was generated.

I am not sure whether I need to clean cache or do something to make it work.

The error displayed on _vendor/robsontenorio/laravel-keycloak-guard/src/KeycloakGuard.php: Line 41_
```
    try {

      $this->decodedToken = Token::decode($this->request->bearerToken(), $this->config['realm_public_key']);

    } catch (\Exception $e) {

      throw new TokenException($e->getMessage());

    }
```

- I am using Laravel 8

**Comment by haizad** [comment]
I need to wait several seconds, only then it will return the full decoded JWT token.

**Comment by dwiyudirayia** [comment]
Yeah, i have issue with that. How to fix?

**Comment by haizad** [comment]
> Yeah, I have same issue with that. How to fix?

Finally someone have the same issue. :D

**Comment by robsontenorio** [comment]
I am on the latest L8 version and can't reproduce. 

This problem occours to any account? Or specifics one?

Please, see https://github.com/auth0/auth0-PHP/issues/56

- Maybe something related to  server time sync

**Comment by haizad** [comment]
Thank you very much sir. I follow the link provided, and turns out it related with leeway in the php-jwt. It works now!

**Comment by HengBrandon** [comment]
@haizad Can you show me the code how to fix this?
