### ISSUE TITLE
users table not defined

### ISSUE THREAD

**Issue by maralbe** [robsontenorio/laravel-keycloak-guard#42]
hi, I want to authenticate users between multiple micro services.. and each micro service will have an authentication.. 
I found your package.. and it seems work for me.. but the problem is I don't know how to tell keycloak to use the users of keycloak panel for authentication.. not to lookup in laravel users table, because there is no users table in my services.

please help me with my issue.. or if you have any suggestion to help me find my solution that be great
thank you

**Comment by robsontenorio** [comment]
Please, check the README “load_user_from_database”.
