### ISSUE TITLE
Lumen 8 Always return "401 Unauthorized"

### ISSUE THREAD

**Issue by corinthoneto** [robsontenorio/laravel-keycloak-guard#49]
I send an request: 

GET /www/seas-siscof-servicos/public/api/grupos HTTP/1.1 Accept: */* Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI5XzFQTUhXVW9qdlptQWIxNzhMVFkyU1N0U211RHM0eWkwbEJtNldMQTJBIn0.eyJleHAiOjE2MjYyMDM4NzAsImlhdCI6MTYyNjIwMzU3MCwiYXV0aF90aW1lIjoxNjI2MjAzNTY4LCJqdGkiOiJlYThhMWMyMC1jMTczLTQxYjItOTEzMS00MmI4MzgxNTExNzEiLCJpc3MiOiJodHRwczovL2lkbS1ob21vbG9nYWNhby5wcm9kYW0uYW0uZ292LmJyL2F1dGgvcmVhbG1zL3Npc2NvZiIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiJkYjM4YTIxZi1hOWE1LTQ2OTktYjIzYi0xY2RkMGRlM2NiYjgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJzaXNjb2Ytd2ViIiwibm9uY2UiOiI5MWJhMTlkMi1jNjIxLTQxMjItOWE0Ni1iMWZjMjcyNTg1ZWQiLCJzZXNzaW9uX3N0YXRlIjoiYzBlYzVhZjMtOGE4ZC00NGFlLTkzZmYtZTRhNmJiYTM4YTBjIiwiYWNyIjoiMSIsImFsbG93ZWQtb3JpZ2lucyI6WyIqIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJvcGVuaWQgZW1haWwgcHJvZmlsZSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwibmFtZSI6IkNvcmludGhvIEZlcm5hbmRlcyIsInByZWZlcnJlZF91c2VybmFtZSI6IjczMjk0Nzk5MjY4IiwiZ2l2ZW5fbmFtZSI6IkNvcmludGhvIiwibG9jYWxlIjoicHQtQlIiLCJmYW1pbHlfbmFtZSI6IkZlcm5hbmRlcyIsImVtYWlsIjoiY29yaW50aG9AcHJvZGFtLmFtLmdvdi5iciJ9.HXlPrfrQPXsdLfBmeERZ62v4LFeSsROGaE1-fvhMemiXV6lQZo-62ldGQekQZGzH2_lJzZH5KR95kbifSxkGhX1eHD-x0Yh_Da4S0HWISR4hAh69CbB5HXKTwPzcMRz8ngvqMOItOBEfKdRtIfPsbqypNYhrWM-m84h6IGJWki5amIIWcmWC_vii2jUaLWYO1qygHLcIq3SIeh9yBRRWQzT1XUyGyaoBNwQIY6zUj0JTTSPLMOP_52_5q-y-2WT_7v7Os9Tg1AzXHssEbef-D3IJJtzgbl3vGgWqJAPy4dhKeT4SOSIK4DsUiUBKaOO2kFQOWzE6iOUWRaFj3fBTBg Host: localhost User-Agent: insomnia/2021.4.1

But, always get an "Unauthorized" return

I'm using Lumen 8.0

**Comment by robsontenorio** [comment]
This kind of message is related to Lavel Authorization mechanisms. 

This package has a different config for Lumen, please, double check the README and make sure if all is fine.

**Comment by corinthoneto** [comment]
Thanks @robsontenorio for reply. I will check the docs again.
