### ISSUE TITLE
Undefined property

### ISSUE THREAD

**Issue by kzsolt7** [robsontenorio/laravel-keycloak-guard#51]
Tech stack: laravel 8, keykcloak 14

First request: please describe the KEYCLOAK_ALLOWED_RESOURCES example in the .env file
Second request: I have attached a picture, I get this error message
![image](https://user-images.githubusercontent.com/26775163/131405063-b6341ee9-6ec1-450b-b1ec-59d045430b11.png)

Thanks

**Comment by robsontenorio** [comment]
There is not such property on source code. Did you modified source code locally ? I can't see where I can help.

https://github.com/robsontenorio/laravel-keycloak-guard/blob/master/src/KeycloakGuard.php#L46
