### ISSUE TITLE
[Keycloak Guard] Signature verification failed

### ISSUE THREAD

**Issue by josefrola2021** [robsontenorio/laravel-keycloak-guard#52]
Hello, I am experiencing problems with the validation of the signature in laravel ^ 8.54, it does not validate the signature, I debugged the library and it gives an error in the openssl_verify of the JWT.php class line 264, the parameters of the token, signature, key , The algorithm is correct, you can see that they arrive, but when validating the signature, it throws an error.

KeycloakGuard\Exceptions\TokenException: [Keycloak Guard] Signature verification failed in file  
![Captura de Pantalla 2021-09-09 a la(s) 17 38 52](https://user-images.githubusercontent.com/88092159/132898061-54ef199e-c5cf-40f7-a132-39d38a600f61.png)
vendor/robsontenorio/laravel-keycloak-guard/src/KeycloakGuard.php on line 44

**Comment by robsontenorio** [comment]
Same #48
