### ISSUE TITLE
[Feature] Validate token using userInfo endpoint

### ISSUE THREAD

**Issue by mrtnzagustin** [robsontenorio/laravel-keycloak-guard#55]
I am planning to create a custom guard in my laravel backend code, based on your llb, but adding the control of the token via userInfo endpoint. Would you like to add this feature?

**Comment by robsontenorio** [comment]
@mrtnzagustin I would like to keep current behavior: this package does not call any external resource. It is passive by design.

**Comment by mrtnzagustin** [comment]
I understand, thanks for the lib it was very useful.
