### ISSUE TITLE
Error: Call to undefined method Illuminate\Auth\DatabaseUserProvider::getModel() when not loading from DB

### ISSUE THREAD

**Issue by LarsKerff** [robsontenorio/laravel-keycloak-guard#59]
When I disable KEYCLOAK_LOAD_USER_FROM_DATABASE, this error will appear:

Error: Call to undefined method Illuminate\Auth\DatabaseUserProvider::getModel()

I want to load the user from keycloak first, because I'm not sure if it exists in the DB.

**Comment by robsontenorio** [comment]
Please, review the README. That option does exactly what do you want.

**Comment by LarsKerff** [comment]
I know what it does, however as soon as I disable the KEYCLOAK_LOAD_USER_FROM_DATABASE it will give an error, test it yourself.
