### ISSUE TITLE
Avoid resource_access control

### ISSUE THREAD

**Issue by enrico-bellanti** [robsontenorio/laravel-keycloak-guard#61]
I'd like to avoid the resource_access control, because i would like to manage directly from my backend, i connot find any solution around if not delete directly the control in the Guard.
It would be great have a configuration at Keycloak.init(), but i cannot find it.
Any solutions?

**Comment by kabircse** [comment]
> I'd like to avoid the resource_access control, because i would like to manage directly from my backend, i connot find any solution around if not delete directly the control in the Guard. It would be great have a configuration at Keycloak.init(), but i cannot find it. Any solutions?

I am also facing this error in api call(postman) ?

**Comment by kabircse** [comment]
> > I'd like to avoid the resource_access control, because i would like to manage directly from my backend, i connot find any solution around if not delete directly the control in the Guard. It would be great have a configuration at Keycloak.init(), but i cannot find it. Any solutions?
> 
> I am also facing this error in api call(postman) ?

I solved this issue. 
I have to create a user role under the client. After then I have to put these roles name in keycloak.php as resources name.
