### ISSUE TITLE
TokenException

### ISSUE THREAD

**Issue by gvalmana** [robsontenorio/laravel-keycloak-guard#62]
Hello how can I avoid that mi API Restfull return KeycloakGuard\Exceptions\TokenException: [Keycloak Guard] Expired token in file and error 500 when the keycloak access token is expired, I attached below the screen of postman answer, sorry for my bad english and thanks for your help
![imagen](https://user-images.githubusercontent.com/15802266/156990868-38411cbb-2e65-4ab9-88f5-942fea7009b7.png)

**Comment by pierrevensy** [comment]
> Hello how can I avoid that mi API Restfull return KeycloakGuard\Exceptions\TokenException: [Keycloak Guard] Expired token in file and error 500 when the keycloak access token is expired, I attached below the screen of postman answer, sorry for my bad english and thanks for your help ![imagen](https://user-images.githubusercontent.com/15802266/156990868-38411cbb-2e65-4ab9-88f5-942fea7009b7.png)

I have the same issue

**Comment by robsontenorio** [comment]
Every token issued on Keycloak has a TTL (expiration). You can change this setting on Keycloak for your client. This package only validates if it has expired.
