### ISSUE TITLE
Support access token via query param

### ISSUE THREAD

**Issue by AubreyHewes** [robsontenorio/laravel-keycloak-guard#63]
*Hi,  I could not find if this issue has been discussed before.*

Currently this project only supports sending the access token via authorization header (bearer token). I have a use case where we also need to support sending the access token via query param / form input. 

Possibly a method like what is used in the Laravel [TokenGuard](https://github.com/laravel/framework/blob/1bbe5528568555d597582fdbec73e31f8a818dbc/src/Illuminate/Auth/TokenGuard.php#L97) would be the answer.

**Comment by robsontenorio** [comment]
Resolved by #77
