### ISSUE TITLE
(Lumen) Publising issue

### ISSUE THREAD

**Issue by Momodedf** [robsontenorio/laravel-keycloak-guard#7]
Configuration and user providers are not published.

php artisan vendor:publish  --provider="KeycloakGuard\KeycloakGuardServiceProvider"
"Nothing to publish for tag []."

**Comment by robsontenorio** [comment]
What is your Laravel/Lumen version?

**Comment by Momodedf** [comment]
Hi, I'm using Lumen 5.7, I must say I'm new to Laravel/Lumen.
I read php artisan config:clear would help, ben this command does not exists for lumen à guess.

I'ld like to provide a merge request for config_path usage but I can't test it.

**Comment by robsontenorio** [comment]
I am sorry, but Lumen has a different setup. Just tested this package on Laravel.

**Comment by robsontenorio** [comment]
From my experience, I recommend you use Laravel even for API Backend project. Lumen has many caveats and missing blocks. 

Just edit RouteServiceProvide for “api” default routes and you are done.

**Comment by Momodedf** [comment]
Thank you, I did the job in AuthServiceProvider.
If it's ok with you I'ld like to make a pull request for token validation (HTTP call to keycloak) in KeycloakGuard::validateResources as a configurable feature.

**Comment by robsontenorio** [comment]
Yes, you can do it! Please, just provide a related test (see folder /tests).
