### ISSUE TITLE
Validate "aud" and "azp" claims?

### ISSUE THREAD

**Issue by lauritzh** [robsontenorio/laravel-keycloak-guard#79]
(REMOVED)

**Comment by lauritzh** [comment]
I played around a bit further.
When you request an `access_token` for client_id `client1` that includes `client2` and `client3` within `resource_access`, `client2` and `client3` are also included within the `aud` claim:
```json
{
[...]
  "azp": "client1",
  "aud": [
    "client2",
    "client3"
  ],
  "resource_access": {
    "client1": {
      "roles": [
        "foo",
      ]
    },
    "client2": {
      "roles": [
        "foo",
      ]
    },
    "client3": {
      "roles": [
        "foo",
      ]
   },
 }
[...]
}
```
   
In my scenario, I am using the *laravel-keycloak-guard* on `client2` and `client3`. IMHO, each client must therefore also validate that their identifier is included within the `aud` claim.

**Comment by robsontenorio** [comment]
I am not expert on SSO/Keycloak, just provided the basics validations. 

If you are able, please , submit a PR with tests and docs.

**Comment by lauritzh** [comment]
Hi @robsontenorio,

thank you very much for your response!
Would you mind switching to a [confidential security advisory draft](https://docs.github.com/en/github/managing-security-vulnerabilities/about-github-security-advisories) and deleting this public issue to discuss further details?

I will try to find the time to provide a PR draft this weekend. 

Best regards,
Lauritz
