### ISSUE TITLE
Call to undefined method KeycloakGuard\KeycloakGuard::attempt()

### ISSUE THREAD

**Issue by Chernitsov** [robsontenorio/laravel-keycloak-guard#8]
Hi and first of all a praise for the development, but unfortunately I have a problem with authentication.

My steps:

1. Installed a fresh Laravel instance..
2. `php artisan make:auth`
3.` composer require robsontenorio/laravel-keycloak-guard`
4. `php artisan vendor:publish  --provider="KeycloakGuard\KeycloakGuardServiceProvider"`
5. changed some parts in `config/auth.php` like the [documentation](https://github.com/robsontenorio/laravel-keycloak-guard)
6. added properties to the .env

`KEYCLOAK_REALM_PUBLIC_KEY="************************************"
KEYCLOAK_LOAD_USER_FROM_DATABASE=
KEYCLOAK_USER_PROVIDER_CREDENTIAL="email"
KEYCLOAK_TOKEN_PRINCIPAL_ATTRIBUTE=
KEYCLOAK_APPEND_DECODED_TOKEN=
KEYCLOAK_ALLOWED_RESOURCES="https://***/auth"`

7. create a new route in api.php

```php
Route::group(['middleware' => 'auth:api'], function () {
    Route::resource('blog', 'Api\BlogController');
});
```

each time if i call the url /api/blog i was redirect to the /login.. then if i want to authenticate, i get this error:

`Call to undefined method KeycloakGuard\KeycloakGuard::attempt()`

Am I doing something wrong?

**Comment by robsontenorio** [comment]
@Chernitsov can you publish this repository. There are many possibilites. Thanks!

**Comment by Chernitsov** [comment]
Hi @robsontenorio, i used it wrong, I did it right and it works! Thank you!

**Comment by Jenkiiz** [comment]
Have the same issue, what was the error please ?

**Comment by shineirvin** [comment]
Hey @Chernitsov how did you solved it ?

**Comment by abhiways** [comment]
instead of attempt() use check()
