### ISSUE TITLE
Unable to extend the guard

### ISSUE THREAD

**Issue by pkarczmarczyk94** [robsontenorio/laravel-keycloak-guard#81]
All KeycloakGuard's properites and methods are private. When we want to overwrite the class to add some additional logic it makes it more complicated. The question is if private is  by design or can we change the props to be protected. 

We will be happy to provide a PR with the changes if you accept it.

Thanks for the grat package!

**Comment by robsontenorio** [comment]
Could you name a couple of use cases ?

**Comment by pkarczmarczyk94** [comment]
The main use case is checking addiitonal claims in token. We also had a need to add additional properties to user model from token when decoding it.

A bit different topic relating to that is we are working on multi realms for keycloak where we need different configuration for each realm guards and currently we created a fork for that, but if you agree we'll also could create PR for multirealm support.

Making methods protected insead of private would make it easier to extend if needed.

**Comment by robsontenorio** [comment]
Hmm....I see.

Please, at first submit a PR for make it `protected` and I will merge it.

If you can, after that, submit another PR with quick draft  for multi realms. So, we can take a look together.

Thanks!

**Comment by lotyp** [comment]
@pkarczmarczyk94 I also am interested in this PR, can help, if needed

**Comment by SolveSoul** [comment]
Since the PR above was deleted and never merged I took the liberty to recreate the same PR. #94
