### ISSUE TITLE
PR code is taken by maintainer

### ISSUE THREAD

**Issue by AubreyHewes** [robsontenorio/laravel-keycloak-guard#82]
Every PR the maintainer choses to integrate, maintainer takes as own code. You will not be acknowledged as a contributor.

For example https://github.com/robsontenorio/laravel-keycloak-guard/pull/64

**Comment by robsontenorio** [comment]
I am sorry, but you don’t know the full context whiling I was trying to merge everything together. 

I do this work on my spare time and  “stars“ or “green squares” on my GitHub profile timeline won’t change anything for me. 

If you wish I can transfer this repo to your name and you get all the honor.
